FROM eclipse-temurin:11.0.14.1_1-jdk as flyway
RUN apt-get update \
    && apt-get install -y python3-pip \
    && pip3 install sqlfluff==1.2.1

WORKDIR /flyway

ARG UNAME=testuser
ARG UID=1000
ARG GID=1000

RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME

ENTRYPOINT ["/bin/bash"]
CMD ["/flyway/mvnw"]

FROM flyway as redgate

RUN curl -L https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -o packages-microsoft-prod.deb \
  && dpkg -i packages-microsoft-prod.deb \
  && rm packages-microsoft-prod.deb
RUN apt-get update \
    && apt-get install -y apt-transport-https \
    && apt-get update \
    && apt-get install -y dotnet-runtime-6.0
