--
-- Copyright 2010-2017 Boxfuse GmbH
--
-- INTERNAL RELEASE. ALL RIGHTS RESERVED.
--

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EVENTO_TIPO]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[EVENTO_TIPO](
		[id] [int] IDENTITY(1,1) NOT NULL,
		[descricao] [varchar](255) COLLATE Latin1_General_CI_AS NULL,
	PRIMARY KEY CLUSTERED 
	(
		[id] ASC
	)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
END
GO