--
-- Copyright 2010-2017 Boxfuse GmbH
--
-- INTERNAL RELEASE. ALL RIGHTS RESERVED.
--
-- Must
-- be
-- exactly
-- 13 lines
-- to match
-- community
-- edition
-- license
-- length.
--

CREATE TABLE CTP_STATUS
(
    STATUS_NAME  VARCHAR(35)  NOT NULL,
    STATUS_VALUE VARCHAR(256) NOT NULL,
    INSERT_TS    TIMESTAMP(6) NOT NULL,
    UPDATE_TS    TIMESTAMP(6) NOT NULL
);

ALTER TABLE "CTP_STATUS" ADD CONSTRAINT "PK_CTP_STATUS" PRIMARY KEY ("STATUS_NAME");