--
-- Copyright 2010-2017 Boxfuse GmbH
--
-- INTERNAL RELEASE. ALL RIGHTS RESERVED.
--

TRUNCATE TABLE "CTP_STATUS" IGNORE DELETE TRIGGERS IMMEDIATE;
ALTER TABLE "CTP_STATUS" RENAME COLUMN "STATUS_VALUE" TO "STATUS_ENABLED";
ALTER TABLE "CTP_STATUS" ALTER COLUMN "STATUS_ENABLED" SET DATA TYPE smallint;