--
-- Copyright 2010-2018 Boxfuse GmbH
--
-- INTERNAL RELEASE. ALL RIGHTS RESERVED.
--
-- Must
-- be
-- exactly
-- 13 lines
-- to match
-- community
-- edition
-- license
-- length.
--

--
-- TT FUNCTION
--
CREATE TABLE TT_FUNCTION
(
   CODE            VARCHAR(10) NOT NULL,
   LANG            VARCHAR(10) NOT NULL,
   TEXT_SHORT      VARCHAR(20),
   TEXT_LONG       VARCHAR(80),
   VALID_FROM      DATE NOT NULL,
   VALID_TO        DATE NOT NULL,
   CREATED         DATE NOT NULL,
   INVALIDATED     DATE,
   CREATED_BY      VARCHAR(32) NOT NULL,
   INVALIDATED_BY  VARCHAR(32) NOT NULL,
   PRIMARY KEY (CODE, LANG)
);

CREATE OR REPLACE VIEW V_TT_FUNCTION
(
   CODE,
   LANG,
   TEXT_SHORT,
   TEXT_LONG,
   VALID_FROM,
   VALID_TO,
   CREATED,
   INVALIDATED,
   CREATED_BY,
   INVALIDATED_BY
)
AS SELECT
   CODE,
   LANG,
   TEXT_SHORT,
   TEXT_LONG,
   VALID_FROM,
   VALID_TO,
   CREATED,
   INVALIDATED,
   CREATED_BY,
   INVALIDATED_BY
FROM
   TT_FUNCTION
;

--
-- TT SOME_KV_PACKAGE
--
CREATE TABLE TT_SOME_KV_PACKAGE
(
   CODE            VARCHAR(10) NOT NULL,
   LANG            VARCHAR(10) NOT NULL,
   TEXT_SHORT      VARCHAR(20),
   TEXT_LONG       VARCHAR(80),
   VALID_FROM      DATE NOT NULL,
   VALID_TO        DATE NOT NULL,
   CREATED         DATE NOT NULL,
   INVALIDATED     DATE,
   CREATED_BY      VARCHAR(32) NOT NULL,
   INVALIDATED_BY  VARCHAR(32) NOT NULL,
   PRIMARY KEY (CODE, LANG)
);

CREATE OR REPLACE VIEW V_TT_SOME_KV_PACKAGE
(
   CODE,
   LANG,
   TEXT_SHORT,
   TEXT_LONG,
   VALID_FROM,
   VALID_TO,
   CREATED,
   INVALIDATED,
   CREATED_BY,
   INVALIDATED_BY
)
AS SELECT
   CODE,
   LANG,
   TEXT_SHORT,
   TEXT_LONG,
   VALID_FROM,
   VALID_TO,
   CREATED,
   INVALIDATED,
   CREATED_BY,
   INVALIDATED_BY
FROM
   TT_SOME_KV_PACKAGE
;

CREATE TABLE PURCHASEPROCEDURE (
id NUMBER(18),
name VARCHAR2(100));

CREATE TABLE Action (
  Id NUMBER(11, 0) NOT NULL,
  Application VARCHAR2(64),
  Module VARCHAR2(64),
  Function VARCHAR2(64),
  Action VARCHAR2(64)
);