--
-- Copyright 2010-2017 Boxfuse GmbH
--
-- INTERNAL RELEASE. ALL RIGHTS RESERVED.
--

CREATE PROCEDURE SP_EQIP_HOURS_AGGRGT_DAY_VIS (
    IN "@MACH_CO_ID"	VARCHAR(15000),
    IN "@START_TIME"	TIMESTAMP,
    IN "@END_TIME"	TIMESTAMP )
  SPECIFIC "SP_EQIP_HOURS_AGGRGT_DAY_VIS_2"
  DYNAMIC RESULT SETS 1
  LANGUAGE SQL
  NOT DETERMINISTIC
  NO EXTERNAL ACTION
  READS SQL DATA
  CALLED ON NULL INPUT
  INHERIT SPECIAL REGISTERS
  OLD SAVEPOINT LEVEL
MAIN:BEGIN
DECLARE V_SECONDS INTEGER DEFAULT 0;
SET V_SECONDS = (SELECT MOD(5,1) * 60 * 60
			FROM SYSIBM.SYSDUMMY1);

RETURN; END;
