--
-- Copyright 2010-2017 Boxfuse GmbH
--
-- INTERNAL RELEASE. ALL RIGHTS RESERVED.
--

CREATE TABLE [dbo].[MY_TABLE] (
ID INT PRIMARY KEY NOT NULL,
DESCRIPTION VARCHAR(20)
)

CREATE SYNONYM [dbo].[MY_SYNONYM] FOR [dbo].[MY_TABLE]