--
-- Copyright 2010-2017 Boxfuse GmbH
--
-- INTERNAL RELEASE. ALL RIGHTS RESERVED.
--

CREATE DATABASE flyway;
CONNECT TO flyway;
GRANT DBADM ON DATABASE TO db2admin;
CREATE SCHEMA db2admin;
TERMINATE;