[flyway]
locations = ["filesystem:/flyway/sql"]
cleanDisabled = false

[environments.default]
url = "jdbc:sqlite:test"

[environments.mongo]
url = "mongodb://sa:flywayPWD000@localhost:27018"

[environments.mongo.flyway]
sqlMigrationSuffixes = [".js"]