--
-- Copyright 2010-2017 Boxfuse GmbH
--
-- INTERNAL RELEASE. ALL RIGHTS RESERVED.
--

CREATE SEQUENCE SEQ_ITEM_ID START WITH 1 INCREMENT BY 1 CACHE 20;
CREATE SEQUENCE SEQ_PFM_USER_ID START WITH 1 INCREMENT BY 1 CACHE 20;
CREATE SEQUENCE SEQ_PFM_ACCOUNT_ID START WITH 1 INCREMENT BY 1 CACHE 20;