--
-- Copyright 2010-2017 Boxfuse GmbH
--
-- INTERNAL RELEASE. ALL RIGHTS RESERVED.
--

CREATE ROLE flyway LOGIN PASSWORD 'flyway';
CREATE DATABASE flyway_db
  WITH OWNER = flyway ENCODING = 'UTF8' TABLESPACE = pg_default;