--
-- Copyright 2010-2017 Boxfuse GmbH
--
-- INTERNAL RELEASE. ALL RIGHTS RESERVED.
--

DROP DATABASE IF EXISTS flyway_db;
DROP DATABASE IF EXISTS flyway_1;
DROP DATABASE IF EXISTS flyway_2;
DROP DATABASE IF EXISTS flyway_3;
DROP USER flyway;
